/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EditGuideIdRouteImport } from './routes/edit.$guideId'
import { Route as RunGuideIdRouteImport } from './routes/run.$guideId'
import { Route as SceneGuideIdRouteImport } from './routes/scene.$guideId'
import { Route as SourcesGuideIdRouteImport } from './routes/sources.$guideId'
import { Route as TrainingGuideIdRouteImport } from './routes/training.$guideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EditGuideIdRoute = EditGuideIdRouteImport.update({
  id: '/edit/$guideId',
  path: '/edit/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunGuideIdRoute = RunGuideIdRouteImport.update({
  id: '/run/$guideId',
  path: '/run/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneGuideIdRoute = SceneGuideIdRouteImport.update({
  id: '/scene/$guideId',
  path: '/scene/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesGuideIdRoute = SourcesGuideIdRouteImport.update({
  id: '/sources/$guideId',
  path: '/sources/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingGuideIdRoute = TrainingGuideIdRouteImport.update({
  id: '/training/$guideId',
  path: '/training/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/edit/$guideId': typeof EditGuideIdRoute
  '/run/$guideId': typeof RunGuideIdRoute
  '/scene/$guideId': typeof SceneGuideIdRoute
  '/sources/$guideId': typeof SourcesGuideIdRoute
  '/training/$guideId': typeof TrainingGuideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/edit/$guideId': typeof EditGuideIdRoute
  '/run/$guideId': typeof RunGuideIdRoute
  '/scene/$guideId': typeof SceneGuideIdRoute
  '/sources/$guideId': typeof SourcesGuideIdRoute
  '/training/$guideId': typeof TrainingGuideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/edit/$guideId': typeof EditGuideIdRoute
  '/run/$guideId': typeof RunGuideIdRoute
  '/scene/$guideId': typeof SceneGuideIdRoute
  '/sources/$guideId': typeof SourcesGuideIdRoute
  '/training/$guideId': typeof TrainingGuideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/settings'
    | '/edit/$guideId'
    | '/run/$guideId'
    | '/scene/$guideId'
    | '/sources/$guideId'
    | '/training/$guideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/settings'
    | '/edit/$guideId'
    | '/run/$guideId'
    | '/scene/$guideId'
    | '/sources/$guideId'
    | '/training/$guideId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/settings'
    | '/edit/$guideId'
    | '/run/$guideId'
    | '/scene/$guideId'
    | '/sources/$guideId'
    | '/training/$guideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  EditGuideIdRoute: typeof EditGuideIdRoute
  RunGuideIdRoute: typeof RunGuideIdRoute
  SceneGuideIdRoute: typeof SceneGuideIdRoute
  SourcesGuideIdRoute: typeof SourcesGuideIdRoute
  TrainingGuideIdRoute: typeof TrainingGuideIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$guideId': {
      id: '/edit/$guideId'
      path: '/edit/$guideId'
      fullPath: '/edit/$guideId'
      preLoaderRoute: typeof EditGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$guideId': {
      id: '/run/$guideId'
      path: '/run/$guideId'
      fullPath: '/run/$guideId'
      preLoaderRoute: typeof RunGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$guideId': {
      id: '/scene/$guideId'
      path: '/scene/$guideId'
      fullPath: '/scene/$guideId'
      preLoaderRoute: typeof SceneGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$guideId': {
      id: '/sources/$guideId'
      path: '/sources/$guideId'
      fullPath: '/sources/$guideId'
      preLoaderRoute: typeof SourcesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$guideId': {
      id: '/training/$guideId'
      path: '/training/$guideId'
      fullPath: '/training/$guideId'
      preLoaderRoute: typeof TrainingGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  EditGuideIdRoute: EditGuideIdRoute,
  RunGuideIdRoute: RunGuideIdRoute,
  SceneGuideIdRoute: SceneGuideIdRoute,
  SourcesGuideIdRoute: SourcesGuideIdRoute,
  TrainingGuideIdRoute: TrainingGuideIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
