/**
 * "Get to Know Andrew (Demo)" — deterministic public demo fixture.
 *
 * Andrew is a fictional team member used to demonstrate onboarding-style
 * GuideForge content; every fact in this fixture is synthetic and marked as
 * demo provenance. The fixture is built with the normal guide schema, the
 * command bus, the source pipeline, and content-addressed procedural assets —
 * it exercises real product primitives, never a parallel demo code path.
 *
 * Seeding is idempotent: an existing local demo copy (including one modified
 * by the visitor) is never overwritten implicitly; use resetDemoGuide() for
 * that. All entity IDs are fixed UUIDs so repeated seeds converge on the same
 * canonical state.
 */
import { generateProceduralGlb } from '@guideforge/assets';
import type { GuideCommand } from '@guideforge/commands';
import { applyCommands, freshGuideState, GUIDE_COMMAND_TYPES } from '@guideforge/commands';
import type { ContentHash, EntityId } from '@guideforge/domain';
import { sha256Hex } from '@guideforge/domain';
import type { GuideSnapshot, TrainingState } from '@guideforge/guide-schema';
import { openDb, OpfsAssetStore } from '@guideforge/storage-web';
import { AssetLibrary, ensureSeedCatalog } from '../services/assetLibrary';
import {
  closeGuide,
  createGuideWithId,
  deleteGuideLocalData,
  dispatchCommand,
  getGuideMeta,
} from '../services/guideStore';
import { addSource } from '../services/sourceStudio';

export const DEMO_GUIDE_VERSION = 1;

/** Stable, well-known demo guide id (UUID-shaped per EntityId contract). */
export const DEMO_GUIDE_ID = 'a0000000-0000-4000-8000-000000000001' as EntityId;

export const DEMO_GUIDE_TITLE = 'Get to Know Andrew (Demo)';

/** Fixed timestamp so seeded snapshots are byte-deterministic across runs. */
const FIXED_OCCURRED_AT = '2026-01-01T00:00:00.000Z';

let idSeq = 0;
function fixedId(): EntityId {
  idSeq += 1;
  return `a0000000-0000-4000-8000-${String(idSeq).padStart(12, '0')}` as EntityId;
}

function command(commandType: string, payload: Record<string, unknown>): GuideCommand {
  return {
    commandId: `demo-cmd-${fixedId()}`,
    commandType,
    actorId: 'demo-seeder',
    guideId: DEMO_GUIDE_ID,
    origin: 'system-normalization',
    occurredAt: FIXED_OCCURRED_AT,
    payload,
  };
}

/**
 * Bundled synthetic profile source (`demo/andrew-profile.md`). Headings and
 * list items become citable regions through the normal ingestion pipeline.
 */
export const DEMO_PROFILE_MARKDOWN = [
  '# Andrew — fictional onboarding profile (demo data)',
  '',
  '> This document is synthetic demo content created for the GuideForge',
  '> public demo. Andrew is not a real person and none of these facts',
  '> describe a real team member.',
  '',
  '# Role and working style',
  '',
  '- Andrew is a fictional lab automation engineer who prefers small,',
  '  well-labeled workspaces.',
  '- He checks calibration before every run and records a measurement note.',
  '',
  '# Communication preferences',
  '',
  '- Prefers concise written summaries after each procedure.',
  '- Asks for photos of any setup that deviates from the standard layout.',
  '',
  '# Workbench safety basics',
  '',
  '- Keep liquids at least ten centimetres away from powered equipment.',
  '- Verify the workbench surface is dry before placing instruments.',
].join('\n');

/** Deterministic SHA-256 for a procedural asset template's generated bytes. */
function proceduralHash(template: Parameters<typeof generateProceduralGlb>[0]): ContentHash {
  return sha256Hex(generateProceduralGlb(template)) as ContentHash;
}

/**
 * Pure builder: the exact command sequence that materializes the demo guide.
 * Citations reference real ingested-source regions resolved by `resolveRegion`.
 */
export function buildDemoCommands(
  sourceHash: ContentHash,
  resolveRegion: (needle: RegExp) => string | null,
): GuideCommand[] {
  idSeq = 0;
  const taskMeet = fixedId();
  const stepRole = fixedId();
  const stepComms = fixedId();
  const stepOutcome = fixedId();

  const taskBench = fixedId();
  const stepBench = fixedId();
  const stepInstrument = fixedId();
  const stepSafety = fixedId();

  const taskCheck = fixedId();
  const stepCheckIntro = fixedId();
  const stepCheckFinish = fixedId();

  const objectiveId = fixedId();
  const itemCommunication = fixedId();
  const itemSafety = fixedId();
  const itemCalibration = fixedId();

  const roleRegion = resolveRegion(/working style/i);
  const commsRegion = resolveRegion(/communication preferences/i);
  const safetyRegion = resolveRegion(/safety basics/i);

  const citationFor = (regionId: string | null) => (regionId ? [{ sourceHash, regionId }] : []);

  const training: TrainingState = {
    competencies: [
      {
        competencyId: fixedId(),
        title: 'Collaborate effectively with a fictional engineer',
        description: 'Demo competency covering communication preferences and safe workbench setup.',
        objectiveIds: [objectiveId],
        citations: [],
        criticality: 'core',
      },
    ],
    objectives: [
      {
        objectiveId,
        verb: 'Describe',
        target: "Andrew's role, communication preferences, and workbench safety rules",
        conditions: 'Using only the bundled demo profile source',
        criterion: 'Answer all three knowledge-check items correctly',
        stepIds: [stepRole, stepComms, stepSafety],
        citations: citationFor(roleRegion),
        criticality: 'core',
      },
    ],
    assessmentItems: [
      {
        itemId: itemCommunication,
        objectiveId,
        prompt: 'How does Andrew prefer to receive updates after a procedure?',
        interaction: 'single-choice',
        options: [
          { optionId: fixedId(), text: 'A concise written summary' },
          { optionId: fixedId(), text: 'An unscheduled drop-in visit' },
          { optionId: fixedId(), text: 'No updates at all' },
        ],
        scoringRule: { correctOptionIds: [] },
        rationale: 'The demo profile states he prefers concise written summaries.',
        feedback: {
          correct: 'Correct — written summaries match his stated preference.',
          incorrect: 'Re-read the Communication preferences section.',
        },
        citations: citationFor(commsRegion),
        criticality: 'core',
        reviewState: 'reviewed',
      },
      {
        itemId: itemSafety,
        objectiveId,
        prompt: 'Where should liquids be kept relative to powered equipment?',
        interaction: 'single-choice',
        options: [
          { optionId: fixedId(), text: 'At least ten centimetres away' },
          { optionId: fixedId(), text: 'Directly underneath, to catch drips' },
          { optionId: fixedId(), text: 'Touching the housing for stability' },
        ],
        scoringRule: { correctOptionIds: [] },
        rationale: 'The safety section requires ten centimetres of separation.',
        feedback: {
          correct: 'Correct — separation prevents spills reaching powered gear.',
          incorrect: 'Check the Workbench safety basics section.',
        },
        citations: citationFor(safetyRegion),
        criticality: 'core',
        reviewState: 'reviewed',
      },
      {
        itemId: itemCalibration,
        objectiveId,
        prompt: 'What does Andrew check before every run?',
        interaction: 'single-choice',
        options: [
          { optionId: fixedId(), text: 'Calibration, recording a measurement note' },
          { optionId: fixedId(), text: 'The office weather report' },
          { optionId: fixedId(), text: 'Nothing — calibration is annual only' },
        ],
        scoringRule: { correctOptionIds: [] },
        rationale: 'His working style includes a pre-run calibration check.',
        feedback: {
          correct: 'Correct — calibration first, then run.',
          incorrect: 'Review the Role and working style section.',
        },
        citations: citationFor(roleRegion),
        criticality: 'important',
        reviewState: 'reviewed',
      },
    ],
    modules: [
      {
        moduleId: fixedId(),
        title: 'Working with Andrew (demo)',
        objectiveIds: [objectiveId],
        lessonIds: [],
      },
    ],
    lessons: [
      {
        lessonId: fixedId(),
        title: 'Meet Andrew and set up safely',
        stepIds: [stepRole, stepComms, stepBench, stepSafety],
        objectiveIds: [objectiveId],
        activityIds: [],
        citations: citationFor(roleRegion),
      },
    ],
    activities: [
      {
        activityId: fixedId(),
        lessonId: fixedId(),
        title: 'Remediate: re-read the demo profile',
        type: 'reflection',
        stepIds: [stepRole],
        objectiveIds: [objectiveId],
        itemIds: [itemCommunication, itemSafety, itemCalibration],
        citations: citationFor(roleRegion),
      },
    ],
    assessmentBlueprint: {
      blueprintId: fixedId(),
      title: 'Andrew demo knowledge check',
      objectiveIds: [objectiveId],
      itemIds: [itemCommunication, itemSafety, itemCalibration],
      criticalItemIds: [itemSafety],
      passThreshold: 0.8,
      maxAttempts: 3,
      citations: [],
    },
    remediationEdges: [
      {
        edgeId: fixedId(),
        fromItemId: itemCommunication,
        toActivityId: fixedId(),
        trigger: 'incorrect',
        reason: 'Revisit the communication preferences region.',
        citations: citationFor(commsRegion),
      },
    ],
    mastery: {
      requiredCriticalItems: 1,
      passThreshold: 0.8,
      maxAttempts: 3,
      policyVersion: 'mastery-v1',
      requiredObjectiveIds: [objectiveId],
      criticalItemIds: [itemSafety],
    },
  };

  // Wire scoring rules to the actual generated option ids (kept out of the
  // literals above so ids stay single-sourced).
  training.assessmentItems[0]!.scoringRule = {
    correctOptionIds: [training.assessmentItems[0]!.options[0]!.optionId],
  };
  training.assessmentItems[1]!.scoringRule = {
    correctOptionIds: [training.assessmentItems[1]!.options[0]!.optionId],
  };
  training.assessmentItems[2]!.scoringRule = {
    correctOptionIds: [training.assessmentItems[2]!.options[0]!.optionId],
  };

  const workbenchHash = proceduralHash('workbench');
  const pipetteHash = proceduralHash('simple-pipette');

  return [
    command(GUIDE_COMMAND_TYPES.setTitle, {
      title: DEMO_GUIDE_TITLE,
    }),
    // Task 1 — Meet Andrew.
    command(GUIDE_COMMAND_TYPES.addTask, { taskId: taskMeet, title: 'Meet Andrew' }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskMeet,
      stepId: stepRole,
      title: "Read Andrew's role and working style.",
    }),
    command(GUIDE_COMMAND_TYPES.addVerification, {
      stepId: stepRole,
      verificationId: fixedId(),
      text: 'You can name his role and pre-run habit.',
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskMeet,
      stepId: stepComms,
      title: 'Note the communication preferences.',
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskMeet,
      stepId: stepOutcome,
      title: 'State what you will know by the end of this guide.',
    }),
    // Task 2 — Set up Andrew's workbench.
    command(GUIDE_COMMAND_TYPES.addTask, {
      taskId: taskBench,
      title: "Set up Andrew's workbench",
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskBench,
      stepId: stepBench,
      title: 'Place the workbench asset in your scene.',
    }),
    command(GUIDE_COMMAND_TYPES.addTool, {
      stepId: stepBench,
      toolId: fixedId(),
      name: 'Levelled bench mat',
    }),
    command(GUIDE_COMMAND_TYPES.addStepMedia, {
      stepId: stepBench,
      referenceId: fixedId(),
      assetHash: workbenchHash,
      mimeType: 'model/gltf-binary',
      kind: 'model',
      caption: 'Procedural CC0 workbench (demo seed catalog)',
    }),
    command(GUIDE_COMMAND_TYPES.addVerification, {
      stepId: stepBench,
      verificationId: fixedId(),
      text: 'Workbench model is attached to the step.',
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskBench,
      stepId: stepInstrument,
      title: 'Attach the pipette instrument next to the beaker rack.',
    }),
    command(GUIDE_COMMAND_TYPES.addStepMedia, {
      stepId: stepInstrument,
      referenceId: fixedId(),
      assetHash: pipetteHash,
      mimeType: 'model/gltf-binary',
      kind: 'model',
      caption: 'Procedural CC0 pipette (demo seed catalog)',
    }),
    command(GUIDE_COMMAND_TYPES.addValue, {
      stepId: stepInstrument,
      valueId: fixedId(),
      label: 'Pipette volume range',
      value: '10–1000 µL',
      unit: 'µL',
    }),
    command(GUIDE_COMMAND_TYPES.addWarning, {
      stepId: stepInstrument,
      warningId: fixedId(),
      severity: 'warning',
      message: 'Demo warning: keep liquids at least 10 cm from powered equipment (synthetic rule).',
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskBench,
      stepId: stepSafety,
      title: 'Confirm the bench surface is dry before placing instruments.',
    }),
    command(GUIDE_COMMAND_TYPES.addVerification, {
      stepId: stepSafety,
      verificationId: fixedId(),
      text: 'Surface inspected and dry.',
    }),
    // Task 3 — Knowledge check.
    command(GUIDE_COMMAND_TYPES.addTask, {
      taskId: taskCheck,
      title: 'Knowledge check',
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskCheck,
      stepId: stepCheckIntro,
      title: 'Take the three-item knowledge check in the training player.',
    }),
    command(GUIDE_COMMAND_TYPES.addCondition, {
      stepId: stepCheckIntro,
      conditionId: fixedId(),
      text: 'Complete tasks 1 and 2 before starting the check.',
    }),
    command(GUIDE_COMMAND_TYPES.addStep, {
      taskId: taskCheck,
      stepId: stepCheckFinish,
      title: 'Finish: review your result and remediation hints.',
    }),
    // Training program + cited objective/assessments.
    command(GUIDE_COMMAND_TYPES.addObjective, {
      objectiveId,
      verb: training.objectives[0]!.verb,
      target: training.objectives[0]!.target,
      conditions: training.objectives[0]!.conditions,
      criterion: training.objectives[0]!.criterion,
      stepIds: [...training.objectives[0]!.stepIds],
      citations: training.objectives[0]!.citations.map((c) => ({ ...c })),
      criticality: 'core',
    }),
    ...training.assessmentItems.map((item) =>
      command(GUIDE_COMMAND_TYPES.addAssessmentItem, {
        itemId: item.itemId,
        objectiveId: item.objectiveId,
        prompt: item.prompt,
        interaction: item.interaction,
        options: item.options.map((o) => ({ ...o })),
        scoringRule: { ...item.scoringRule },
        rationale: item.rationale,
        feedback: { ...item.feedback! },
        citations: item.citations.map((c) => ({ ...c })),
        criticality: item.criticality,
      }),
    ),
    command(GUIDE_COMMAND_TYPES.replaceTraining, { training }),
    ...training.assessmentItems.map((item) =>
      command(GUIDE_COMMAND_TYPES.reviewAssessmentItem, {
        itemId: item.itemId,
        reviewState: 'reviewed' as const,
      }),
    ),
  ];
}

export interface EnsureDemoGuideResult {
  guideId: EntityId;
  created: boolean;
  version: number;
}

/**
 * Seed assets + the demo guide locally. Idempotent: if the demo guide already
 * exists in this browser (even modified), nothing is overwritten.
 */
export async function ensureDemoGuide(): Promise<EnsureDemoGuideResult> {
  const existingMeta = await getGuideMeta(DEMO_GUIDE_ID);
  if (existingMeta) {
    return { guideId: DEMO_GUIDE_ID, created: false, version: DEMO_GUIDE_VERSION };
  }

  const database = openDb();
  await ensureSeedCatalog(new AssetLibrary(database, new OpfsAssetStore(database)));

  const session = await createGuideWithId(DEMO_GUIDE_ID, DEMO_GUIDE_TITLE);
  try {
    const ingest = await addSource(
      { db: session.db, assets: session.assets },
      {
        guideId: DEMO_GUIDE_ID,
        originalFilename: 'demo-andrew-profile.md',
        bytes: new TextEncoder().encode(DEMO_PROFILE_MARKDOWN),
      },
    );
    if (!ingest.verdict.accepted || ingest.source.status === 'failed') {
      throw new Error(
        `demo source ingestion failed: ${ingest.verdict.reason ?? ingest.source.receipt?.error ?? 'unknown error'}`,
      );
    }
    const sourceHash = ingest.source.sha256 as ContentHash;
    const regions = ingest.source.regions;
    const resolveRegion = (needle: RegExp): string | null =>
      regions.find((region) => needle.test(region.excerpt))?.regionId ?? null;

    for (const cmd of buildDemoCommands(sourceHash, resolveRegion)) {
      await dispatchCommand(session, cmd);
    }
  } finally {
    await closeGuide(session);
  }
  return { guideId: DEMO_GUIDE_ID, created: true, version: DEMO_GUIDE_VERSION };
}

/**
 * Explicitly wipe the visitor's local demo copy (guide doc, metadata,
 * sessions, evidence, proposals) and recreate the pristine fixture.
 * Destructive by definition — callers must confirm with the user first.
 */
export async function resetDemoGuide(): Promise<EnsureDemoGuideResult> {
  await deleteGuideLocalData(DEMO_GUIDE_ID);
  return ensureDemoGuide();
}

/** Build the pristine demo snapshot purely (no storage) — test/validation seam. */
export function buildPristineDemoSnapshot(sourceHash: ContentHash): GuideSnapshot {
  return applyCommands(
    freshGuideState(DEMO_GUIDE_ID, ''),
    buildDemoCommands(sourceHash, () => null),
  );
}
